version: '3'
services:
  cif:
    build:
      dockerfile: ./Dockerfile-ubuntu
      context: https://github.com/CommunityHoneyNetwork/stingar-cif.git#v0.1.2
    image: cif:ubuntu
    privileged: true
    ports:
      - "5000:5000"
  elasticsearch:
    user: "1000"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.0
    volumes:
      - .devel/elasticsearch/data:/usr/share/elasticsearch/data:z
      - .devel/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:z
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  kibana:
    user: "1000"
    image: docker.elastic.co/kibana/kibana-oss:6.5.0
    volumes:
      - .devel/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:z
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - fluentd
    links:
      - elasticsearch:elasticsearch
  fluentd:
    build:
      context: .devel/fluentd
    volumes:
      - .devel/fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf:z
      - .devel/fluentd/conf/fluent.conf:/etc/conf.d/es.conf:z
      - ./fluentd-outputs/out_stingar.rb:/etc/fluent/plugin/out_cif.rb:z
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    links:
#      - cif:cif
      - elasticsearch:elasticsearch
    env_file:
      - stingar.env
  fluentbit:
    image: fluent/fluent-bit
    links:
      - fluentd:fluentd
    volumes:
      - .devel/fluentbit/conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    env_file:
      - stingar.env
  cowrie:
    build:
      dockerfile: Dockerfile
      context: ./fluentd-cowrie
    image: cowrie:ubuntu
    ports:
      - "22:2222"
      - "23:2223"
    depends_on:
      - fluentd
    links:
      - fluentbit:fluentbit
    env_file:
      - stingar.env
  stingarapi:
    build:
      dockerfile: ./Dockerfile
      context: stingar-api
    image: stingar-api:ubuntu
    ports:
      - "8000:8000"
    links:
      - elasticsearch:elasticsearch
